// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fynrwnustzouevpqsdzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bnJ3bnVzdHpvdWV2cHFzZHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Njk4NzYsImV4cCI6MjA3MjQ0NTg3Nn0.cii2fSjxhy7NO61u3e7oqg5XtcTnddZ6c48M4JqIka4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});